const boar = {
  phenotypes: ["Description of sexualized behavior", "Semen quality"],
  breed: ["Duroc", "Hampshire", "Landrace", "Yorkshire"],
  growthStage: ["Reserve boar", "Stud boars"],
  isolationLocation: ["Cecum", "Colon", "Feces", "Ileum", "Jejunum", "Rectum"],
  experimentalDesign: ["wild boar and domestic pig"],
};

const sow = {
  phenotypes: [
    "Average daily feed intake(ADFI kg/d)",
    "Average  daily weight gain(ADGkg/d)",
    "Backfat  Thickness",
    "Birth  weigh",
    "Fat  deposition",
    "Feed  conversion efficiency(FCR)",
    "Immune  performance",
    "Intramuscular  fat content",
    "Litter size",
    "Metabolites  of intestinal flora",
    "Milk yield",
    "Muscle-to-fat  ratio",
    "Number of  litters per litter",
    "Ocular  muscle area",
    "Oestrous  interval",
    "Service  life",
    "Weaning  diarrhea rate",
    "Weaning  nest weight",
    "Weaning  survival rate",
    "Weaning  weight",
  ],
  breed: [
    "Bama mini-pigs",
    "Duroc ×  Landrace × Yorkshire",
    "Göttingen  minipigs",
    "Landrace",
    "Landrace ×  Yorkshire",
    "Meishan",
    "Rongchang",
    "Yorkshire",
  ],
  growthStage: [
    "Farrowing  Sow",
    "Gilts",
    "Lactational Sow",
    "Multiparous Sow",
    "Pregnant Sow",
    "Primiparous Sow",
  ],
  isolationLocation: [
    "Areolar  skin",
    "Cecum",
    "Colon",
    "Feces",
    "Ileum",
    "Jejunum",
    "Rectum",
    "Vaginal",
  ],
  experimentalDesign: [
    "Colostrum  and milk component",
    "Cross breeding",
    "Dietary fibers with varying  physicochemical properties(lignocellulose (LC), modified cassava starch (MCS)  and konjac flour (KF))",
    "Fructose and Resistant Starch",
    "Immune performance of piglets",
    "In vitro gut modeling",
    "L-Arginine",
    "Lysozyme",
    "Maternal and neonatal gut  microbial",
    "Maternal feces",
    "Maternal fermented diet (MFD)",
    "Maternal milk and fecal  microbes",
    "Maternal obesity",
    "Microbes from the maternal and  surrounding environments",
    "Perinatal period",
    "Periparturient longitudinal  changes in sow microbiota composition",
    "Reciprocal cross-fostering  model",
    "Salmonella",
    "Simulation of in vitro  fermentation methods",
    "Xylanase",
    "Yeast culture",
  ],
};

const piglet = {
  phenotypes: [
    "Average daily feed intake(ADFI kg/d)",
    "Average  daily weight gain(ADGkg/d)",
    "Backfat  Thickness",
    "Birth  weigh",
    "Fat  deposition",
    "Feed  conversion efficiency(FCR)",
    "Immune  performance",
    "Intramuscular  fat content",
    "Litter size",
    "Metabolites  of intestinal flora",
    "Milk yield",
    "Muscle-to-fat  ratio",
    "Number of  litters per litter",
    "Ocular  muscle area",
    "Oestrous  interval",
    "Service  life",
    "Weaning  diarrhea rate",
    "Weaning  nest weight",
    "Weaning  survival rate",
    "Weaning  weight",
  ],
  breed: [
    "Bama mini-pigs",
    "Commercial  genotype (YxL)",
    "commercial  pigs",
    "Congjiang  miniature and Landrace × Yorkshire",
    "Crossbred  pig",
    "Crossbred  piglets (50% Pietrain × 25% Landrace* 25% Large White)",
    "DNA600 ×  PIC1050",
    "Duroc",
    "Duroc ×  Landrace",
    "Duroc ×  Landrace × Yorkshire",
    "Duroc ×  Yorkshire and Duroc × Landrace",
    "Jinhua  pigs",
    "Landrace",
    "Landrace ×  Piétrain",
    "Landrace ×  Piétrain × Yorkshire",
    "Landrace ×  Yorkshire",
    "Local  breed(Gaec de Calvignac, St. Vincent d’Autejac, France)",
    "Local  breed(Gansu, China)",
    "Meishan",
    "Mixed-breed  (Duroc, Hampshire, Yorkshire, and Landrace)",
    "Native(Foshan,China)  × Duroc",
    "native(Korean)  × Yorkshire",
    "Norwegian  Landrace",
    "Piétrain ×  Yorkshire",
    "Rongchang",
    "Suhuai  pigs(Jiangsu, China)",
    "Sushan  pigs",
    "Tempo × Topigs-20",
    "Top Pi ×  Topigs 20",
    "Topics  hybrid × Piétrain",
    "Topigs-20",
    "TOPIGS-40",
    "Yorkshire",
  ],
  growthStage: ["Pre Weaned Piglets", "Weaned  Piglets"],
  isolationLocation: [
    "Cecum",
    "Colon",
    "Duodenum",
    "Feces",
    "Ileum",
    "Intestine",
    "Jejunum",
    "Rectum",
    "Stomach",
  ],
  experimentalDesign: [
    "A mixture  of antibiotics (50 mg/kg olaquindox,50 mg/kg oxytetracycline calcium, and 50  mg/kg kitasamycin)",
    "Aerotolerant pig fecal  microbiota",
    "Alfalfa meal",
    "Allium extract",
    "Amoxicillin",
    "Amoxicillin,colistin  sulphate,Sanacore EN，Nutriad International N.V",
    "Antibiotic growth promoter",
    "Apple Pomace",
    "Bacillus mixture",
    "Bovine colostrum (BC), milk  replacer (MR) or sow milk (SM)",
    "Bran variants",
    "Butyrate",
    "Calcium-phosphorus",
    "Carbadox (antibiotic), copper  sulfate and zinc oxide (metals)",
    "Carbadox and ASP250  [chlortetracycline, sulfamethazine, and penicillin]",
    "Ceftiofur crystalline free  acid,ceftiofur hydrochloride,oxytetracycline,procaine penicillin  G,tulathromycin",
    "Clostridium Butyricum",
    "Copper",
    "Corn bran",
    "Corn-Soy blend fortified with  phosphorus",
    "Deoxynivalenol (DON) and  zearalenone (ZEN)",
    "Dietary Inulin",
    "Dietary Soluble and Insoluble  Fiber",
    "Dietary tuna dark muscle  enzymatic hydrolysis and cooking drip supplementations",
    "Exogenous catalase (CAT)",
    "FE and farm of birth",
    "Galacto-Oligosaccharides",
    "Galactooligosaccharides and  Polydextrose",
    "Gentamicin and a mixture of  Bacillus (B.) licheniformis, B. subtilis and B.",
    "Gentamycin sulfate",
    "Glycyl-Glutamine",
    "Grape seed meal (GSM)",
    "High-fiber rapeseed",
    "Implications of Tributyrin",
    "In-Feed Antibiotic Carbadox",
    "L. reuteri,chlortetracycline",
    "Lactic acid and Bacillus  subtilis",
    "Lactobacillus plantarum strain  JDFM LP11",
    "L-Tryptophan",
    "Lysine restriction",
    "Medium-chain fatty acids  (MCFA)",
    "Mixed fiber",
    "Montmorillonite",
    "Multi-component lipid  emulsions",
    "Mushroom substrates (FSMS)",
    "Natural Pig Plasma  Immunoglobulins",
    "Olaquindox,oxytetracycline  calcium,kitasamycin",
    "Phytase",
    "Protected butyrate",
    "Protein restriction",
    "Protein restriction and  succedent realimentation",
    "Resistant potato starch (RPS)",
    "Sodium butyrate or sodium  heptanoate protected with medium-chain fatty acids",
    "Sodium butyrate,benzoic acid",
    "Soluble Fiber and Insoluble  Fiber",
    "Spent Cider Yeast",
    "Synbiotic",
    "Tylosin phosphate",
    "Virginiamycin and synbiotic",
    "Yeast probiotics",
    "Zinc oxide (ZnO）",
    "Zinc Oxide/Zeolite",
    "ZnO",
  ],
};

const growingFinishingPig = {
  phenotypes: [
    "Average daily feed intake(ADFI kg/d)",
    "Average  daily weight gain(ADGkg/d)",
    "Backfat  Thickness",
    "Birth weigh",
    "Fat  deposition",
    "Feed  conversion efficiency(FCR)",
    "Immune  performance",
    "Intramuscular  fat content",
    "Metabolites  of intestinal flora",
    "Muscle-to-fat  ratio",
    "Ocular  muscle area",
    "Quality of  meat",
    "Weaning  diarrhea rate",
    "Weaning  survival rate",
    "Weaning  weight",
  ],
  breed: [
    "Bama mini-pigs",
    "Chinese  Shanxi Black Pigs; Yorkshire",
    "Commercial  pigs",
    "Crossbred  pig",
    "Duroc",
    "Diannan small ear pigs",
    "Duroc ×  Landrace × Yorkshire",
    "Duroc × Iberian",
    "Iberian  pigs",
    "Jinhua pigs",
    "Jinhua  pigs; Landrace",
    "Landrace ×  Piétrain × Yorkshire",
    "Landrace ×  Yorkshire",
    "Nero Siciliano pigs",
    "Piétrain",
    "Topigs 20  × Tempo",
    "Yorkshire",
  ],
  growthStage: [
    "Growing-finishing  Pigs(50-80kg)",
    "Growing-finishing  Pigs(80-100kg)",
    "Growing-finishing  pigs(100-150kg)",
    "Growing-finishing  Pigs(20-50kg)",
  ],
  isolationLocation: [
    "Cecum",
    "Colon",
    "Duodenum",
    "Feces",
    "Ileum",
    "Jejunum",
    "Rectum",
    "Stomach",
  ],
  experimentalDesign: [
    "A raw  potato starch (RPS, high in resistant starch)",
    "Appetite",
    "Body weight",
    "Burn resuscitation strategy",
    "Cefuroxime, streptomycin",
    "Co-fermented skimmed rice bran",
    "Cysteamine",
    "DPF strategy and TPF strategy",
    "Enterotype",
    "Extreme feed conversion ratios",
    "Fecal microbiota transfer",
    "Fecal microbiota  transplantation (FMT),lipid metabolism",
    "Fermented Corn-Soybean Meal",
    "Fermented Corn–Soybean Meal",
    "Fermented Mao-tai lees",
    "Genotyping",
    "Hermetia illucens",
    "Hermetia illucens,BSF",
    "High resistant starch",
    "Host Genome",
    "In Vitro Fermentation  Characteristics of cellulose, arabinoxylan, β-glucan and glucomannan",
    "Inulin",
    "Lactobacillus delbrueckii",
    "Lberian pig intestinal tract",
    "Lincomycin",
    "Low crude protein diet",
    "Moderate dietary protein  restriction",
    "Nutrient metabolism",
    "Polyphenol",
    "Saccharomyces cerevisiae  boulardii CNCM I-1079",
    "Salbutamol",
    "Salmonella",
    "Shanxi Black Pig and Large  White Pig",
    "Stevia residue extract  supplementation",
    "Strain, farm and weaning age",
    "Tapioca starch, corn starch,  or pea starch",
    "Transglycosylated cornstarch  (TGS)",
    "Xylo-oligosaccharide",
  ],
};

const countries = [
    'Australia',
    'Austria',
    'Barcelona',
    'Belgium',
    'California',
    'Canada',
    'China',
    'Danish',
    'Denmark',
    'England',
    'France',
    'Germany',
    'Ireland',
    'Irish',
    'Italy',
    'Jeju  Island',
    'Korea',
    'Netherlands',
    'Norway',
    'Romania',
    'South  Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'USA'
]

export { boar, sow, piglet, growingFinishingPig, countries };
