const searchSelectDatas = {
  category: ["Boar", "Growing-finishing Pigs", "Piglets", "Sow"],
  isolationLocation: [
    "Areolar skin",
    "Cecum",
    "Colon",
    "Duodenum",
    "Feces",
    "Ileum",
    "Intestine",
    "Jejunum",
    "Rectum",
    "Stomach",
    "Vaginal",
  ],
  country: [
    "Australia",
    "Austria",
    "Barcelona",
    "Belgium",
    "California",
    "Canada",
    "China",
    "Danish",
    "Denmark",
    "England",
    "France",
    "Germany",
    "Ireland",
    "Irish",
    "Italy",
    "Jeju Island",
    "Korea",
    "Netherlands",
    "Norway",
    "Romania",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "USA",
  ],
  phenotypes: [
    "Average daily feed intake(ADFI kg/d)",
    "Average daily weight gain(ADGkg/d)",
    "Backfat Thickness",
    "Birth weigh",
    "Description of sexualized behavior",
    "Fat deposition",
    "Feed conversion efficiency(FCR)",
    "Immune performance",
    "Intramuscular fat content",
    "Litter size",
    "Meat stock ratio",
    "Metabolites of intestinal flora",
    "Milk yield",
    "Muscle-to-fat ratio",
    "Number of litters per litter",
    "Ocular muscle area",
    "Oestrous interval",
    "Quality of meat",
    "Semen quality",
    "Service life",
    "Weaning diarrhea rate",
    "Weaning nest weight",
    "Weaning survival rate",
    "Weaning weight",
  ],
  breed: [
    "Aachen  minipigs",
    "Bama  mini-pigs",
    "Chinese  Shanxi Black Pigs; Yorkshire",
    "Commercial  genotype (YxL)",
    "Commercial  pigs",
    "Congjiang  miniature and Landrace × Yorkshire",
    "Crossbred  pig",
    "Crossbred  piglets (50% Pietrain × 25% Landrace* 25% Large White)",
    "DNA600 ×  PIC1050",
    "Duroc",
    "Duroc ×  Landrace",
    "Duroc ×  Landrace × Yorkshire",
    "Duroc × Yorkshire  and Duroc × Landrace",
    "Duroc × Iberian",
    "German  Landrace",
    "German  Landrace × minipigs",
    "Göttingen  minipigs",
    "Iberian  pigs",
    "Jinhua  pigs",
    "Landrace",
    "Landrace  × Piétrain",
    "Landrace  × Piétrain × Yorkshire",
    "Landrace  × Yorkshire",
    "Local  breed(Gaec de Calvignac, St. Vincent d’Autejac, France)",
    "Local  breed(Gansu, China)",
    "Meishan",
    "Micro-pigs  (crossbred)",
    "Mixed-breed  (Duroc, Hampshire, Yorkshire, and Landrace)",
    "Native(Foshan,China)  × Duroc",
    "native(Korean)  × Yorkshire",
    "Norwegian  Landrace",
    "p53 pigs",
    "Piétrain",
    "Piétrain  × Yorkshire",
    "Rongchang",
    "Suhuai pigs(Jiangsu,  China)",
    "Sushan  pigs",
    "Tempo × Topigs-20",
    "Top Pi ×  Topigs 20",
    "Topics hybrid × Piétrain",
    "Topigs 20 × Tempo",
    "Topigs-20",
    "TOPIGS-40",
    "Wuzhishan  pigs",
    "Yorkshire",
    "Tibetan pigs",
    "Nero Siciliano pigs",
    "Diannan small ear pigs",
    "Red River Hog"
  ],
  sex: ["famale", "male"],
  growthStage: [
    "Farrowing Sow",
    "Gilts",
    "Growing-finishing  pigs(100-150kg)",
    "Growing-finishing  Pigs(20-50kg)",
    "Growing-finishing Pigs(50-80kg)",
    "Growing-finishing  Pigs(80-100kg)",
    "Lactational  Sow",
    "Multiparous  Sow",
    "Pre Weaned Piglets",
    "Pregnant  Sow",
    "Primiparous  Sow",
    "Reserve boar",
    "Stud boars",
    "Weaned  Piglets",
  ],
  experimentalDesign:{
    earlyWeaningMeasures: [
        "12 days",
        "14 days",
        "14 days (early weaning), 21  days (a common weaning age in intensive pig farming), 28 days (idem), and 42  days (late weaning)",
        "18 days",
        "20 days",
        "21 days",
        "23 days",
        "24 days",
        "24~26 days",
        "25 days",
        "26 days",
        "26±1 days",
        "26±2 days",
        "28 days",
        "28±2 days",
        "29 days",
        "30 days",
        "30 ± 2 days",
        "63 days",
        "Experiment1:28day;Experiment2:21day",
        "Weaned at 45 ± 1  days;D45;E35;F20",
    ],
    feedAdditives: [
        "Feed additives",
        "L-Arginine",
        "A mixture of antibiotics (50  mg/kg olaquindox,50 mg/kg oxytetracycline calcium, and 50 mg/kg kitasamycin)",
        "Aerotolerant pig fecal  microbiota",
        "Allium extract",
        "Amoxicillin",
        "Amoxicillin,colistin  sulphate,Sanacore EN，Nutriad International N.V",
        "Antibiotic growth promoter",
        "Bacillus mixture",
        "Bifidobacterium thermophilum  RBL67 and fructo-oligosaccharides",
        "Butyrate",
        "Calcium-phosphorus",
        "Carbadox (antibiotic), copper  sulfate and zinc oxide (metals)",
        "Carbadox and ASP250  [chlortetracycline, sulfamethazine, and penicillin]",
        "Ceftiofur crystalline free  acid,ceftiofur hydrochloride,oxytetracycline,procaine penicillin  G,tulathromycin",
        "Cefuroxime, streptomycin",
        "Clostridium Butyricum",
        "Co-fermented skimmed rice bran",
        "Copper",
        "Cysteamine",
        "Deoxynivalenol (DON) and  zearalenone (ZEN)",
        "Dietary fibers with varying  physicochemical properties(lignocellulose (LC), modified cassava starch (MCS)  and konjac flour (KF))",
        "Dietary Inulin",
        "Dietary Soluble and Insoluble  Fiber",
        "Dietary tuna dark muscle  enzymatic hydrolysis and cooking drip supplementations",
        "distiller’s dried grains with  solubles (DDGS)",
        "Exogenous catalase (CAT)",
        "Fermented Corn–Soybean Meal",
        "Fermented Mao-tai lees",
        "Fructose and Resistant Starch",
        "Galacto-Oligosaccharides",
        "Galactooligosaccharides and  Polydextrose",
        "Gentamicin and a mixture of  Bacillus (B.) licheniformis, B. subtilis and B.",
        "Gentamycin sulfate",
        "Glycyl-Glutamine",
        "Grape seed meal (GSM)",
        "Implications of Tributyrin",
        "In-Feed Antibiotic Carbadox",
        "Inulin",
        "L. reuteri,chlortetracycline",
        "Lactic acid and Bacillus  subtilis",
        "Lactobacillus delbrueckii",
        "Lactobacillus plantarum strain  JDFM LP11",
        "Lincomycin",
        "L-Tryptophan",
        "Lysine restriction",
        "Lysozyme",
        "Medium-chain fatty acids  (MCFA)",
        "Mixed fiber",
        "Moderate dietary protein restriction",
        "Montmorillonite",
        "Multi-component lipid  emulsions",
        "Mushroom substrates (FSMS)",
        "Natural Pig Plasma  Immunoglobulins",
        "Olaquindox,oxytetracycline  calcium,kitasamycin",
        "Phytase",
        "Polyphenol",
        "Protected butyrate",
        "Protein restriction and  succedent realimentation",
        "Saccharomyces cerevisiae  boulardii CNCM I-1079",
        "Salbutamol",
        "Sodium butyrate or sodium  heptanoate protected with medium-chain fatty acids",
        "Sodium butyrate,benzoic acid",
        "Soluble Fiber and Insoluble  Fiber",
        "Spent Cider Yeast",
        "Stevia residue extract  supplementation",
        "Synbiotic",
        "Tapioca starch, corn starch,  or pea starch",
        "Tylosin phosphate",
        "Virginiamycin and synbiotic",
        "Xylanase",
        "Xylo-oligosaccharide",
        "Yeast culture",
        "Yeast probiotics",
        "Zinc oxide (ZnO)",
        "Zinc Oxide/Zeolite",
        "ZnO",
    ],
    feedingPractices: [
        "A raw  potato starch (RPS, high in resistant starch)",
        "Alfalfa meal",
        "Apple Pomace",
        "Bovine colostrum (BC), milk  replacer (MR) or sow milk (SM)",
        "Bran variants",
        "Corn bran",
        "Corn-Soy blend fortified with  phosphorus",
        "Fermented Corn-Soybean Meal",
        "Hermetia illucens",
        "Hermetia illucens,BSF",
        "High resistant starch",
        "High-fiber rapeseed",
        "Low crude protein diet",
        "Protein restriction",
        "Resistant potato starch (RPS)",
        "Transgenic Bt rice containing  the Cry1Ab protein",
        "Transglycosylated cornstarch  (TGS)",
    ],
    others: [
        "A  non-alcoholic fatty liver disease (nAfLD)-related disorder in french SLAdd  minipig",
        "Adaptation to high altitude  conditions",
        "Age",
        "AO blood types",
        "Appetite",
        "Behaviour",
        "Black soldier fly larvae  (BSFL)",
        "Body weight",
        "Burn resuscitation strategy",
        "Ceftiofur",
        "Changes in gut microbiota  before and after weaning",
        "Cholestasis in preterm pigs",
        "Collection of bacterial  isolates from the pig intestine",
        "Colostrum and milk component",
        "Comparison of Fecal Microbial  Communities between White and Black Pigs",
        "Cross breeding",
        "Cross cultivation",
        "Cross-Fostering Piglet Model",
        "Diarrhea resistance",
        "Diet complexity and growth  performance",
        "Different breeds, growth  periods and genders",
        "DPF strategy and TPF strategy",
        "Drinking Water T emperature  and Flow Rate during Cold Season",
        "Dynamic changes of pig gut  microbiome following the ages",
        "Dystrophy",
        "E. coli bivalent vaccine",
        "Enterotoxigenic Escherichia  coli Infection",
        "Enterotype",
        "Environmental complexity",
        "Expression of  neurotransmitters",
        "Extreme feed conversion ratios",
        "Faecal microbiota of pigs  (Duroc, Long White and Yorkshire) before and after cohabitation",
        "FE and farm of birth",
        "Fecal microbiota transfer",
        "Fecal microbiota  transplantation (FMT),lipid metabolism",
        "Fecal source identification  using random forest",
        "Fumonisin-Exposure",
        "Genotyping",
        "Glässer's disease,nasal  microbiota",
        "Host Genome",
        "Immune performance of piglets",
        "In Vitro Fermentation  Characteristics of cellulose, arabinoxylan, β-glucan and glucomannan",
        "In vitro gut modeling",
        "Intrauterine growth restricted",
        "Lberian pig intestinal tract",
        "Low birth weight",
        "Low-birth-weight",
        "Maternal and neonatal gut  microbial",
        "Maternal feces",
        "Maternal fermented diet (MFD)",
        "Maternal milk and fecal  microbes",
        "Maternal obesity",
        "Metabolite Signature",
        "Microbes from the maternal and  surrounding environments",
        "Mucine 4 and Fucosyltransferase 1 genetic variants",
        "Necrotizing enterocolitis  (NEC)",
        "New neonatal porcine diarrhoea",
        "Newborn Preterm Pigs",
        "Nutrient metabolism",
        "PDCoV",
        "Perinatal period",
        "Periparturient longitudinal  changes in sow microbiota composition",
        "Phylogenetic network analysis",
        "Piglet diarrhea",
        "Porcine circovirus type 2  (PCV2)",
        "Porcine epidemic diarrhea  (PED)",
        "Reciprocal cross-fostering  model",
        "Rectal swabs",
        "Reduction of dietary crude  protein (CP) level",
        "Salmonella",
        "Salmonella infection",
        "Shanxi Black Pig and Large  White Pig",
        "Short-chain fatty acids",
        "Simulated piglet small  intestine",
        "Simulation of in vitro  fermentation methods",
        "Strain, farm and weaning age",
        "Sulfatereducing bacteria",
        "The influence of the gut  microbiota on African swine fever susceptibility",
        "Use of antibiotics",
        "Vitro multi-compartment  gastrointestinal model for piglet",
        "Weaning age",
        "Weaning transition",
    ]
  }
};

// 处理experimentalDesign数据为级联选择器的格式
const experimentalDesign = searchSelectDatas.experimentalDesign;
const experimentalDesignKeys = Object.keys(experimentalDesign);
const experimentalDesignValues = Object.values(experimentalDesign);
const experimentalDesignData = [];
for (let i = 0; i < experimentalDesignKeys.length; i++) {
  experimentalDesignData.push({
    value: experimentalDesignKeys[i],
    label: experimentalDesignKeys[i],
    children: experimentalDesignValues[i].map((item) => {
      return {
        value: item,
        label: item,
      };
    }),
  });
}
searchSelectDatas.experimentalDesign = experimentalDesignData;

export default searchSelectDatas;



